// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: fileserver.proto

package fileserverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_fileserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_fileserver_proto_rawDescGZIP(), []int{0}
}

func (x *FileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_fileserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_fileserver_proto_rawDescGZIP(), []int{1}
}

func (x *FileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_fileserver_proto protoreflect.FileDescriptor

const file_fileserver_proto_rawDesc = "" +
	"\n" +
	"\x10fileserver.proto\x12\n" +
	"fileserver\")\n" +
	"\vFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"(\n" +
	"\fFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent2K\n" +
	"\vFileService\x12<\n" +
	"\aGetFile\x12\x17.fileserver.FileRequest\x1a\x18.fileserver.FileResponseB\x0fZ\r/fileserverpbb\x06proto3"

var (
	file_fileserver_proto_rawDescOnce sync.Once
	file_fileserver_proto_rawDescData []byte
)

func file_fileserver_proto_rawDescGZIP() []byte {
	file_fileserver_proto_rawDescOnce.Do(func() {
		file_fileserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fileserver_proto_rawDesc), len(file_fileserver_proto_rawDesc)))
	})
	return file_fileserver_proto_rawDescData
}

var file_fileserver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fileserver_proto_goTypes = []any{
	(*FileRequest)(nil),  // 0: fileserver.FileRequest
	(*FileResponse)(nil), // 1: fileserver.FileResponse
}
var file_fileserver_proto_depIdxs = []int32{
	0, // 0: fileserver.FileService.GetFile:input_type -> fileserver.FileRequest
	1, // 1: fileserver.FileService.GetFile:output_type -> fileserver.FileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fileserver_proto_init() }
func file_fileserver_proto_init() {
	if File_fileserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fileserver_proto_rawDesc), len(file_fileserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fileserver_proto_goTypes,
		DependencyIndexes: file_fileserver_proto_depIdxs,
		MessageInfos:      file_fileserver_proto_msgTypes,
	}.Build()
	File_fileserver_proto = out.File
	file_fileserver_proto_goTypes = nil
	file_fileserver_proto_depIdxs = nil
}
