# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fileserver.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fileserver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66ileserver.proto\x12\nfileserver\"\x1f\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1f\n\x0c\x46ileResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x32K\n\x0b\x46ileService\x12<\n\x07GetFile\x12\x17.fileserver.FileRequest\x1a\x18.fileserver.FileResponseB\x0fZ\r/fileserverpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fileserver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\r/fileserverpb'
  _globals['_FILEREQUEST']._serialized_start=32
  _globals['_FILEREQUEST']._serialized_end=63
  _globals['_FILERESPONSE']._serialized_start=65
  _globals['_FILERESPONSE']._serialized_end=96
  _globals['_FILESERVICE']._serialized_start=98
  _globals['_FILESERVICE']._serialized_end=173
# @@protoc_insertion_point(module_scope)
